### ISSUE TITLE
遇到一点问题

### ISSUE THREAD

**Issue by wow-ww** [BUAASE-Slime/Questionnaire-Planet-Django#3]
使用python manage.py makemigrations，无法迁移数据库，还请指教一下呀？😊

**Comment by huanngzh** [comment]
请问是否按照 README 中的提示，在 **utils/secrets.py** 配置好数据库信息？

建议配上您的运行报错截图，才好判断出错原因。

**Comment by BFlameSwift** [comment]
建议把错误码完整贴出来。。
可能有以下几个原因：之前的数据库文件未删除。数据库连接错误：没有正确链接到数据库等。。也可能是连接的数据库的制定位置已经有了表等等。。

**Comment by BFlameSwift** [comment]
![image](https://user-images.githubusercontent.com/69407642/160156442-294cb2fc-5f6f-4a1b-aada-5b2fb811fed7.png)
我刚刚在 utils/secrets.py 配置好数据库信息，并在数据库中创建制定的数据库。运行图中两项命令即生成了数据库表，可再次注意文件是否被成功填写，并根据报错在此处反馈或是百度求解

**Comment by wow-ww** [comment]
早上好，我的环境是: python 3.8.9 django 3.0

### 1.django utils secrets文件截图
![django-util s-secrets](https://user-images.githubusercontent.com/63279624/160219972-68d4e183-8c1a-4aa4-ba6c-a0704ee6aaa8.png)

### 2.django文件目录
![django文件目录](https://user-images.githubusercontent.com/63279624/160220038-847e8cd6-c839-47c0-bd3d-e514236402b8.png)

### 3.python 报错
![python报错](https://user-images.githubusercontent.com/63279624/160220068-ea960f07-4f4c-4a7c-8861-fe04248bd2d7.png)

### 4.vue globalinfo文件截图
![vue-globalinfo](https://user-images.githubusercontent.com/63279624/160220020-c44a48e3-b06b-413e-98e7-4991db472466.png)

### 5.数据库环境
![phpstudy环境](https://user-images.githubusercontent.com/63279624/160220081-3b48be7f-d296-402a-9c2a-eefd9edbe198.png)
![mysql](https://user-images.githubusercontent.com/63279624/160220083-cc0bef6a-f828-4f4e-b8a4-8b6810251a9d.png)

#### 麻烦了，有读README文档，初次接触django，有些地方看太不明白

**Comment by BFlameSwift** [comment]
在你的**保错**中的No changes detected 表示你已经创建好**生成数据库的文件了**，

**Comment by BFlameSwift** [comment]
> ### 3.python 报错
> ![python报错](https://user-images.githubusercontent.com/63279624/160220068-ea960f07-4f4c-4a7c-8861-fe04248bd2d7.png)


在你的**保错**中的No changes detected 表示你已经创建好**生成数据库的文件了**，并不是运行错误。
接下来使用 `python manage.py migrate ` 来使用这些**生成文件**来**生成数据库表**，你就可以在本地查到到那些表了。
PS： 运行后端前也要填写好 个人邮箱等一系列信息方可运行

**Comment by BFlameSwift** [comment]
另外推荐一下个人的朋友所写的[Django教程](https://super-buaa-2021.github.io/Djangobook/) 。相信看后您便会对Django有一个基本的了解
当然如果想要了解更过关于Django的内容也可自行寻找一些书籍自学，不过个人觉得还未对项目有个大概便直接观看官方文档可能会有些吃力，而主要起查阅作用吧

**Comment by wow-ww** [comment]
谢谢你们~网站已经在本地跑起来啦呜呜呜太感谢啦
另外，你github上所留下的邮箱，能联系到你嘛？
![yx](https://user-images.githubusercontent.com/63279624/160231368-723ccc08-7df2-4c80-ba16-e54aab49c801.png)

**Comment by BFlameSwift** [comment]
嗯嗯可以的，既然解决了那我就关闭issue了哈
